export const TERM_OPTIONS = [
  { value: '7d', label: '7 days' },
  { value: '14d', label: '14 days' },
  { value: '1m', label: '1 month' },
  { value: '2m', label: '2 months' },
  { value: '3m', label: '3 months' },
  { value: '4m', label: '4 months' },
  { value: '5m', label: '5 months' },
  { value: '6m', label: '6 months' },
  { value: '7m', label: '7 months' },
  { value: '8m', label: '8 months' },
  { value: '9m', label: '9 months' },
  { value: '10m', label: '10 months' },
  { value: '11m', label: '11 months' },
  { value: '12m', label: '12 months' },
];